### ISSUE TITLE
Error when going back from sleep

### ISSUE THREAD

**Issue by SighT26** [valinet/ThinkPadLEDControl#2]
Hello! When i going back from sleep mode or from fullscreen (movie for ex.) i get an error: index out of range. Here is the screenshot in russian
![Screenshot_1](https://user-images.githubusercontent.com/74139371/98464833-8b606380-21d6-11eb-9114-211b86e3a954.png)
I use options that controls only keyboard illumination, but power button is also cannot back to ON after sleep. My nb is ThinkPad X280. Thanks for support

**Comment by valinet** [comment]
Sorry for the delay, it is now fixed in 1.6.0.7 (98104c1). Please check out the latest release [here](https://github.com/valinet/ThinkPadLEDControl/releases/tag/1.6.0.7).
